NAME = main 

CC = gcc
CFLAGS = -Wall -Wextra -Werror -I .
RM = rm -rf

SRC = $(wildcard *.c)
OBJS = $(SRC:.c=.o)
HEADER = $(wildcard *.h)

all : $(NAME)
	@echo "compilation completed"

$(NAME): $(OBJS) $(HEADER)
#$(NAME) : $(OBJS)
#	@$(CC) $(FLAGS) $(OBJS) -o $(NAME)
#%.o : %.c $(HEADER)
#	@$(CC) $(FLAGS) -c $

clean :
	@$(RM) $(OBJS)
	@echo "clean completed";
fclean: clean
	@$(RM) $(NAME)
	@echo "full clean completed"
re: fclean all

.PHONY: all clean fclean re
